// main.js — gerado a partir do monólito; edite aqui a partir de agora.
import './styles.css';
import './core/constantes.js';
import './core/periodos.js';
import './core/firebase.js';
import './core/store.js';
import './core/sync-status.js';
import './core/sync.js';
import './core/auth.js';
import './core/app.js';
import './core/datas.js';
import './core/horas.js';
import './features/timer.js';
import './features/validacao.js';
import './features/prazos.js';
import './features/dados.js';
import './ui/base.js';
import './ui/router.js';
import './views/dashboard.js';
import './views/calendario.js';
import './views/pendencias.js';
import './views/diario.js';
import './views/grade.js';
import './views/unitins/hub.js';
import './views/unitins/aulas.js';
import './views/unitins/sincronas.js';
import './views/unitins/entregaveis.js';
import './views/analytics/graficos.js';
import './views/analytics/output.js';
import './views/analytics/analytics.js';
import './views/habitos/habitos.js';
import './views/habitos/estante.js';
import './financas/core.js';
import './financas/util.js';
import './financas/voz.js';
import './financas/view.js';
import './financas/dashboard.js';
import './financas/analytics.js';
import './financas/config.js';
import { FIN_FAT, FIN_IMP, FIN_ST, finAba, finAdiantar, finAdiantarConfirmar, finCartao, finCartaoDel, finColar, finColarAnalisar, finColarImportar, finColarPreview, finComp, finConta, finContaDel, finFatValor, finFixos, finGerarMes, finImpFatura, finImpFaturaAnalisar, finImpFaturaImportar, finImpFaturaPreview, finMeioF, finMesG, finModelo, finModeloDel, finNovoCredito, finSalvarCartao, finSalvarConta, finSalvarFatValor, finSalvarModelo, finToggleConta, finToggleFat, finCatF, finParcModo } from './financas/view.js';
import { abrirPortao, entrarComGoogle, sair, usarOffline } from './core/auth.js';
import { addLog, delLog, limparFiltroDiario, mNovaSessao, refreshHistChips, setDiario, setDiarioAtiv, setDiarioBusca } from './views/diario.js';
import { calAbrir, calAbrirMes, calAnoNav, calDiaModal, calGo, calHoje, calNav, setCalVista } from './views/calendario.js';
import { ckDesc, delCheckin, mCheckin, saveCheckin } from './views/analytics/output.js';
import { closeModal } from './ui/base.js';
import { copiarGrade, cumprirBloco, delBloco, delPeriodo, mBloco, mCopiarGrade, mPeriodo, mPeriodos, salvarSplit, saveBloco, savePeriodo, setVgPeriodo, splitRecalc } from './views/grade.js';
import { copiarRegras, exportData, importData, mDiagnostico } from './features/dados.js';
import { delAula, gerarAulas, mAula, mGerarAulas, saveAula, setAulasEst, setAulasMat, toggleAula, toggleAulaEstudo } from './views/unitins/aulas.js';
import { delEntreg, gerarEntregaveis, mEntreg, mGerarEntregaveis, saveEntreg, setEntregEst, setEntregMat, toggleEntregAndamento, toggleEntregue } from './views/unitins/entregaveis.js';
import { delHabito, mHabito, mhFreqChange, saveHabito, setHbAno, setHbMeses, toggleHabito, toggleHbMes, toggleMhDia, toggleMhExcl } from './views/habitos/habitos.js';
import { delLivro, mLivro, saveLivro } from './views/habitos/estante.js';
import { delMateria, mMateria, resetMateriaStatus, saveMateria, setMateriaStatus, setUni, setUniPeriodo } from './views/unitins/hub.js';
import { delPend, mPendencia, novaPendenciaNoDia, savePend, togglePend } from './views/pendencias.js';
import { delSincrona, delSincronaConfirm, mSincrona, previewSincronas, registrarSincrona, saveSincrona } from './views/unitins/sincronas.js';
import { enableNotifs } from './features/prazos.js';
import { finAnFim, finAnPer } from './financas/analytics.js';
import { finCfg, finEsquecer, finExport, finImport, finSalvarCfg } from './financas/config.js';
import { finCatCor, finCatExcluir, finCatModal, finCatSalvar, finCatSelect } from './financas/categorias.js';
import { finForcarEnvio } from './financas/core.js';
import { finGastoDel, finGastoEditar, finMeioChange, finMicToggle, finNovoManual, finProcessar, finSalvarGasto, finVozAbrir, finVozFechar } from './financas/voz.js';
import { finOcultarDash } from './financas/dashboard.js';
import { finVal } from './financas/util.js';
import { go, toggleSidebar } from './ui/router.js';
import { mMetaSemanal, saveMetaSemanal } from './views/dashboard.js';
import { setAnAno, setAnDias } from './views/analytics/graficos.js';
import { timerClosePanel, timerDiscard, timerOpenPanel, timerPause, timerResume, timerSetArea, timerSetAtividade, timerStart, timerStop } from './features/timer.js';
import { toggleTema } from './core/app.js';
import * as ns0 from './core/constantes.js';
import * as ns1 from './core/periodos.js';
import * as ns2 from './core/firebase.js';
import * as ns3 from './core/store.js';
import * as ns4 from './core/sync-status.js';
import * as ns5 from './core/sync.js';
import * as ns6 from './core/auth.js';
import * as ns7 from './core/app.js';
import * as ns8 from './core/datas.js';
import * as ns9 from './core/horas.js';
import * as ns10 from './features/timer.js';
import * as ns11 from './features/validacao.js';
import * as ns12 from './features/prazos.js';
import * as ns13 from './features/dados.js';
import * as ns14 from './ui/base.js';
import * as ns15 from './ui/router.js';
import * as ns16 from './views/dashboard.js';
import * as ns17 from './views/calendario.js';
import * as ns18 from './views/pendencias.js';
import * as ns19 from './views/diario.js';
import * as ns20 from './views/grade.js';
import * as ns21 from './views/unitins/hub.js';
import * as ns22 from './views/unitins/aulas.js';
import * as ns23 from './views/unitins/sincronas.js';
import * as ns24 from './views/unitins/entregaveis.js';
import * as ns25 from './views/analytics/graficos.js';
import * as ns26 from './views/analytics/output.js';
import * as ns27 from './views/analytics/analytics.js';
import * as ns28 from './views/habitos/habitos.js';
import * as ns29 from './views/habitos/estante.js';
import * as ns30 from './financas/core.js';
import * as ns31 from './financas/util.js';
import * as ns32 from './financas/voz.js';
import * as ns33 from './financas/view.js';
import * as ns34 from './financas/dashboard.js';
import * as ns35 from './financas/analytics.js';
import * as ns36 from './financas/config.js';

/* Ponte para handlers inline (onclick="..."): em módulo ES nada é global por padrão.
   Lista gerada varrendo todos os atributos on* do HTML e dos templates. */
Object.assign(window, { finParcModo, finCatF, finCatCor, finCatExcluir, finCatModal, finCatSalvar, finCatSelect, FIN_FAT, FIN_IMP, FIN_ST, abrirPortao, addLog, calAbrir, calAbrirMes, calAnoNav, calDiaModal, calGo, calHoje, calNav, ckDesc, closeModal, copiarGrade, copiarRegras, cumprirBloco, delAula, delBloco, delCheckin, delEntreg, delHabito, delLivro, delLog, delMateria, delPend, delPeriodo, delSincrona, delSincronaConfirm, enableNotifs, entrarComGoogle, exportData, finAba, finAdiantar, finAdiantarConfirmar, finAnFim, finAnPer, finCartao, finCartaoDel, finCfg, finColar, finColarAnalisar, finColarImportar, finColarPreview, finComp, finConta, finContaDel, finEsquecer, finExport, finFatValor, finFixos, finForcarEnvio, finGastoDel, finGastoEditar, finGerarMes, finImpFatura, finImpFaturaAnalisar, finImpFaturaImportar, finImpFaturaPreview, finImport, finMeioChange, finMeioF, finMesG, finMicToggle, finModelo, finModeloDel, finNovoCredito, finNovoManual, finOcultarDash, finProcessar, finSalvarCartao, finSalvarCfg, finSalvarConta, finSalvarFatValor, finSalvarGasto, finSalvarModelo, finToggleConta, finToggleFat, finVal, finVozAbrir, finVozFechar, gerarAulas, gerarEntregaveis, go, importData, limparFiltroDiario, mAula, mBloco, mCheckin, mCopiarGrade, mDiagnostico, mEntreg, mGerarAulas, mGerarEntregaveis, mHabito, mLivro, mMateria, mMetaSemanal, mNovaSessao, mPendencia, mPeriodo, mPeriodos, mSincrona, mhFreqChange, novaPendenciaNoDia, previewSincronas, refreshHistChips, registrarSincrona, resetMateriaStatus, sair, salvarSplit, saveAula, saveBloco, saveCheckin, saveEntreg, saveHabito, saveLivro, saveMateria, saveMetaSemanal, savePend, savePeriodo, saveSincrona, setAnAno, setAnDias, setAulasEst, setAulasMat, setCalVista, setDiario, setDiarioAtiv, setDiarioBusca, setEntregEst, setEntregMat, setHbAno, setHbMeses, setMateriaStatus, setUni, setUniPeriodo, setVgPeriodo, splitRecalc, timerClosePanel, timerDiscard, timerOpenPanel, timerPause, timerResume, timerSetArea, timerSetAtividade, timerStart, timerStop, toggleAula, toggleAulaEstudo, toggleEntregAndamento, toggleEntregue, toggleHabito, toggleHbMes, toggleMhDia, toggleMhExcl, togglePend, toggleSidebar, toggleTema, usarOffline });

/* Console/depuração/testes: leitura AO VIVO de qualquer export (namespace é live binding). */
const __ns = [ns0, ns1, ns2, ns3, ns4, ns5, ns6, ns7, ns8, ns9, ns10, ns11, ns12, ns13, ns14, ns15, ns16, ns17, ns18, ns19, ns20, ns21, ns22, ns23, ns24, ns25, ns26, ns27, ns28, ns29, ns30, ns31, ns32, ns33, ns34, ns35, ns36];
window.__planner = new Proxy({}, { get: (_, k) => { for (const n of __ns) if (k in n) return n[k]; } });
import { renderSyncBadge, setSync } from './core/sync-status.js';
import { load } from './core/app.js';
import { loadTimerState, renderTimerWidget, timerEnsureTicking } from './features/timer.js';

/* ---------------- Boot ---------------- */
load();
renderSyncBadge();
if(typeof navigator!=='undefined'&&navigator.onLine===false)setSync('offline','sem conexão de rede');
loadTimerState();
timerEnsureTicking();
renderTimerWidget();
